### ISSUE TITLE
errors README

### ISSUE THREAD

**Issue by irenebm** [Nuriadj/plansys2_lpgtd_plugin#2]
The command to set the global variable of the planner have to be:
`echo "export LPGTD=~/bin/lpgtd" >> .bashrc`
And the parameter plan_solver_plugins to set in plansys2_bringup/params/plansys2_params.yaml is:
`["LPGTD"]`

**Comment by RoxanaAN** [comment]
You're right!
Thanks for you comment, I'm going to fix it right now!
